config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  root "users#index"

  resources :search, only: [:index, :show]
  resources :interests
  post 'interest/:id/join', to: 'interests#join', as: 'join_interest'
  post 'interest/:id/leave', to: 'interests#leave', as: 'leave_interest'
  resources :lbgs
  post 'lbg/:id/join', to: 'lbgs#join', as: 'join_lbg'
  post 'lbg/:id/leave', to: 'lbgs#leave', as: 'leave_lbg'

  resources :users, only: [:index, :show]
  resources :announcements
  get 'announcements?tag=:id', to: 'announcements#index', as: 'announcements_tag'

  resources :tags, only: [:index]
  resources :contacts, except: [:index, :show]
  resources :addresses, except: [:index, :show]
  resources :languages, except: [:index, :show]
  resources :educations, except: [:index, :show]
  resources :experiences, except: [:index, :show]
  resources :lbgs, except: [:index, :show]

  post 'comment', to: 'announcements#add_comment', as: 'add_comment'
  delete 'comment/:id', to: 'announcements#del_comment', as: 'del_comment'
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_taggable

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_user!
  before_action only: [:edit, :destroy] do
    user_owns_resource?(Announcement)
  end
  before_action only: [:del_comment] do
    user_owns_resource?(Comment)
  end
  before_action :visited_announcements?, :only => [:index]
  helper_method :sort_column, :sort_direction

  def index
    if params[:tag].nil?
      @announcement = Announcement.all
    else
      @announcement = Announcement.tagged_with(params[:tag])
    end
    @announcements = @announcement.paginate(page: params[:page], per_page: 10).order(sort_column + ' ' + sort_direction)
    @tags = Tag.where("taggings_count > 0").first(10)
    @self_announcements = current_user.announcements
  end

  def edit
    @tags = Tag.all
    @announcement = @resource
    @selected = @announcement.tag_list
  end

  def new
  	@announcement = Announcement.new
  	@tags = Tag.all
  	@selected = nil
  end

  def show
  	@announcement = Announcement.find(params[:id])
  	@user = @announcement.user
  	@comment = Comment.new
  end

  def destroy
    @announcement.tag_list.remove(current_tags)
    @announcement.save!
    @announcement.destroy
    flash[:notice]="You deleted your announcement"
    redirect_to announcements_path
  end

  def add_comment
    @comment = Comment.new(comment_params)
    if @comment.save!
      flash[:success]="You added a new comment!"
      redirect_to announcement_path(comment_params[:announcement_id])
    else
      flash[:alert]="Something went wrong :( Please report this bug at admin@aludir.net"
      redirect_to root_path
    end
  end

  def del_comment
    @announcement = @comment.announcement_id
    @comment.destroy

    flash[:notice]="You deleted your comment successfully"
    redirect_to announcement_path(@announcement)
  end

  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.tag_list.add(new_tags)
    if @announcement.save!
      flash[:success]="You created an announcement successfully!"
      redirect_to announcements_path
    else
      flash[:alert]="Something went wrong :( Please report this bug at admin@aludir.net"
      render_to new_announcement_path
    end
  end

  def update
    @announcement = Announcement.find(params[:id])
    @announcement.tag_list.remove(current_tags - new_tags)
    @announcement.tag_list.add(new_tags - current_tags)

    if @announcement.update(announcement_params)
      flash[:success]="You updated your announcement successfully!"
      redirect_to @announcement
    else
      flash[:alert]="Something went wrong :( Please report this bug at admin@aludir.net"
      render 'edit'
    end
  end

  private
  def announcement_params
    params.require(:announcement).permit(:user_id, :title, :body, :tag_list => [])
  end

  def comment_params
    params.require(:comment).permit(:user_id, :body, :announcement_id)
  end

  def tag_params
    params.require(:tags)
  end

  def sort_column
    Announcement.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end

  def user_owns_comment?
    @comment = Comment.find(params[:id])
    if !user_validation(@comment)
      flash[:alert]="You are not the owner of this comment!"
      redirect_to announcement_path(@comment.announcement.id)
    end
  end

  def visited_announcements?
    current_user.visited_announcements_at = Time.now
    current_user.save!
  end

  def current_tags
    @announcement.tag_list
  end

  def new_tags
    tag_params.values.first.split(',')
  end
end

app/views/announcements/_form.html.erb
<div class="row">
  <div class="col-md-5">

	<%= form_for @announcement, html: {class: "form-group"} do |f| %>
	  <div class="form-group">
	  	<%= f.label :title %>
	    <%= f.text_field :title, required: 'required', placeholder: 'Title', class: 'form-control' %>
	  </div>
	  <div class="form-group">
	  	<%= f.label :body %>
	    <%= f.text_area :body, required: 'required', placeholder: 'Message', class: 'form-control', rows: 10 %>
	  </div>
	  
	  <div class="form-group">
	    <%= fields_for :tags do |tags_fields|%>
	      <%= tags_fields.label :tags%>
	      <%= tags_fields.text_field :values, required: 'required', placeholder: 'Tags',
	      	class: 'js-example-basic-multiple form-control' %>
	    <%end%>
	  </div>
	  
	  <%= f.hidden_field :user_id, {value: current_user.id} %>
	  <% if dom_id == "edit_announcement"%>
	    <%= button_to "Edit!", edit_announcement_path(@announcement), class: "btn btn-success" %>
	    <%= button_to 'Delete', announcement_path(@announcement), method: :delete,
	  data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
	  <%else%>
	    <%= f.submit "Submit!", class: "btn btn-success" %>
	  <%end%>
	<% end %>
  </div>
</div>

app/views/announcements/edit.html.erb
<script>
  var tags = [<% @tags.each do |tag| %>"<%= tag.name %>",<% end %>];

$(document).ready(function() {
  $(".js-example-basic-multiple").val(['<%= @selected.to_s%>']).select2({
  	tags: tags,
  	tokenSeparators: [',', ' ']
  });
});
</script>

<%= render 'form', dom_id: "edit_announcement"%>

app/views/announcements/index.html.erb
<div class="row">
  <div class="col-md-2">
    <h4>Filter by tags</h4>
    <% unless params[:tag].nil? %><%= link_to 'Remove filter?', announcements_path %><%end%>
    <div class="well">
      <% @tags.each do |t| %>
        <% if params[:tag]== t.name %><b><%end%>
            <%= link_to t.name, announcements_tag_path(t.name) %><br/>
        <% if params[:tag] == t.name %></b><%end%>
      <% end %>
    </div>
  </div>
  <div class="col-md-10">
  <h2>Announcements</h2>
    <div class="table-responsive">
    <table class='table table-hover'>
      <thead>
        <tr>
          <th><%= sortable 'title' %></th>
          <th><%= sortable 'user_id', 'Announcer' %></th>
          <th>Tags</th>
          <th><%= sortable 'created_at', 'Date'%></th>
          <th>Comments</th>
        </tr>
      </thead>
  
      <tbody> 
        <% @announcements.each do |announcement| %>
          <tr>
            <td><%= link_to announcement.title, announcement_path(announcement) %></td>
            <td><%= link_to announcement.user.name+' '+announcement.user.surname, user_path(announcement.user.uuid) %></td>
            <td><%= announcement.tag_list.map {|x| (link_to x, announcements_tag_path(x))}.to_sentence(:last_word_connector => ', ', :two_words_connector => ', ').html_safe %></td>
            <td><%= announcement.created_at.strftime("%Y-%m-%d") %></td>
            <td><%= announcement.comments.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <center><%= link_to 'Announce too!', new_announcement_path, class: 'btn btn-success'%></center>
  </div>
  <%= will_paginate @announcements, renderer: BootstrapPagination::Rails, class: 'pull-right' %>
</div>

<div class="row">
  <div class="col-md-12">
    <% unless @self_announcements.empty? %>
    
    <h2>Your announcements</h2>
      <div class="table-responsive">
        <table class='table table-hover'>
          <thead>
            <tr>  
              <th>Title</th>
              <th>Tags</th>
              <th>Date</th>
              <th>Comments</th>
              <th></th>
            </tr>
          </thead>
    
          <tbody>
            <% @self_announcements.each do |announcement| %>
              <tr>
                <td><%= link_to announcement.title, announcement_path(announcement) %></td>
                <td><%= announcement.tag_list %></td>
                <td><%= announcement.created_at.strftime("%Y-%M-%d") %></td>
                <td><%= announcement.comments.count %></td>
                <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <%end%>
  </div>
</div>

app/views/announcements/new.html.erb
<script>
  var tags = [<% @tags.each do |tag| %>"<%= tag.name %>",<% end %>];
  
$(document).ready(function() {
  $(".js-example-basic-multiple").val(['<%= @selected.to_s%>']).select2({
  	tags: tags,
  	tokenSeparators: [',', ' ']
  });
});
</script>

<%= render 'form', dom_id: 'new_announcement'%>

app/views/announcements/show.html.erb
<div class="row">
  <div class="col-md-10">
    
    <div class="row">
    <div class="well col-md-6">
      By: <%= link_to @user.name+' '+@user.surname, user_path(@user) %>
      <br>
      Tags: <%= @announcement.tag_list.map {|x| (link_to x, announcements_tag_path(x))}.to_sentence(:last_word_connector => ', ', :two_words_connector => ', ').html_safe %>
      <br>
      Posted on: <%= @announcement.created_at.strftime("%Y-%m-%d") %>
      <br>
      Last edited at: <%= @announcement.updated_at.strftime("%Y-%m-%d") %>
      <% if @announcement.user.id == current_user.id %>
        <%= link_to 'edit now?', edit_announcement_path %>
      <% end %>
    </div>
    </div>
    <div class="row">
      <h1><%= @announcement.title %></h1>
      
      <div class="lead">
        <%= @announcement.body %>
      </div>
    </div>
    <div ckass="row">
      <hr>
      <h2><i>Comments</i></h2>
      <div class="table-responsive">
        <table class='table table-hover'>
          <thead>
            <tr>
              <th>Name</th>
              <th>Comment</th>
              <th>Date posted</th>
              <th></th>
            </tr>
          </thead>
          <% @announcement.comments.each do |com| %>
            <tr>
              <td><%= link_to com.user.name+' '+com.user.surname, user_path(com.user.uuid) %></td>
              <td><%= com.body %></td>
              <td><%= com.created_at.strftime("%Y-%m-%d") %></td>
              <td><% if com.user_id == current_user.id %><%= link_to 'Delete', del_comment_path(com), method: :delete, data: {confim: 'Are you sure?'}%> <%end%></td>
            </tr>
          <%end%>
        </table>
      </div>
      <hr>
      <h2>New comment</h2>
      
      <%= form_for @comment, url: add_comment_path do |c| %>
        <%= c.text_area :body, required: 'required', placeholder: 'Comment', cols: 50, rows: 2%><br>
        <%= c.hidden_field :user_id, {value: current_user.id} %>
        <%= c.hidden_field :announcement_id, {value: @announcement.id} %>
        <%= c.submit "Post comment!", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>