config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  root "users#index"

  resources :search, only: [:index, :show]
  resources :interests
  post 'interest/:id/join', to: 'interests#join', as: 'join_interest'
  post 'interest/:id/leave', to: 'interests#leave', as: 'leave_interest'
  resources :lbgs
  post 'lbg/:id/join', to: 'lbgs#join', as: 'join_lbg'
  post 'lbg/:id/leave', to: 'lbgs#leave', as: 'leave_lbg'

  resources :users, only: [:index, :show]
  resources :announcements
  get 'announcements?tag=:id', to: 'announcements#index', as: 'announcements_tag'

  resources :tags, only: [:index]
  resources :contacts, except: [:index, :show]
  resources :addresses, except: [:index, :show]
  resources :languages, except: [:index, :show]
  resources :educations, except: [:index, :show]
  resources :experiences, except: [:index, :show]
  resources :lbgs, except: [:index, :show]

  post 'comment', to: 'announcements#add_comment', as: 'add_comment'
  delete 'comment/:id', to: 'announcements#del_comment', as: 'del_comment'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :city
  
  def full_address
    country_name = Country.new(self.country_id)
    [self.street, self.number, self.city.name, self.zip, country_name].to_sentence(:last_word_connector => ', ', :two_words_connector => ', ').html_safe
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_taggable

  validates :title, presence: true
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :contact
end

app/models/city.rb
class City < ApplicationRecord
  has_one :experience
  has_one :address
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :announcement
  
  validates :user_id, presence: true
  validates :announcement_id, presence: true
  validates :body, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_one :experience
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_one :category
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  belongs_to :city
  belongs_to :company

  def company_name
    self.company.name
  end
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :user
end

app/models/lbg.rb
class Lbg < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/search.rb
class Search < ApplicationRecord
  
  def users
    @users ||= find_users
  end

  def self.for(id_search, name, surname, old_surname, nickname)

    # escape for security
    name        = "%#{name}%"
    surname     = "%#{surname}%"
    old_surname = "%#{old_surname}%"
    nickname    = "%#{nickname}%"

    users = User.order(:name)
    users = users.where(id: id_search) if id_search.present?
    users = users.where("name like ?", "%#{name}%") if name.present?
    users = users.where("surname like ?", "%#{surname}%") if surname.present?
    users = users.where("old_surname like ?", "%#{old_surname}%") if old_surname.present?
    users = users.where("nickname like ?", "%#{nickname}%") if nickname.present?
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :announcements
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses
  has_many :educations
  has_many :contacts
  has_many :experiences
  has_many :languages
  has_many :announcements
  has_many :comments
  has_and_belongs_to_many :lbgs
  has_and_belongs_to_many :interests
  validates :uuid, uniqueness: true
  validates :name, presence: true
  validates :surname, presence: true
  validates :birth_date, presence: true

  enum gender: ["Male","Female","Other"]

  def age
    (Date.today - self.birth_date).to_i / 365
  end

  def country
    @countries = Array.new
    @addresses = self.addresses
    @addresses.each do |a|
      @countries << Country.new(a.country_id).name
    end
    @countries.to_sentence
  end

  def field
    @fields = Array.new
    @experiences = self.experiences
    @experiences.each do |e|
      @fields << e.field_of_work
    end
    @fields.to_sentence
  end

  def company
    @companies = Array.new
    @experiences = self.experiences
    @experiences.each do |e|
      @companies << e.company.name
    end
    @companies.to_sentence
  end
end

app/controllers/lbgs_controller.rb
class LbgsController < ApplicationController

  def index
    @lbgs = Lbg.all
  end

  def show
    @lbg = Lbg.find(params[:id])
    @users = @lbg.users
  end

  def join
    if is_member?
      flash[:alert]='You are already part of this LBG'
    else
      flash[:success]='You added this LBG!'
      @lbg.users<< current_user
    end
    redirect_to user_path(current_user.uuid)
  end

  def leave
    if is_member?
      flash[:notice]='You left this group'
      @lbg.users.destroy(current_user)
    else
      flash[:alert]='You are not part of this group'
    end
    redirect_to user_path(current_user.uuid)
  end

  private
  def is_member?
    if params[:action] == "leave"
      @lbg = Lbg.find(params[:id])
    else
      @lbg = Lbg.find(lbg_params[:id])
    end
    @lbg.users.exists?(current_user.id)
  end

  def lbg_params
    params.require(:lbg).permit(:id, :name, :user_id)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      resource.uuid = SecureRandom.hex(n=6)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: :show

  # GET /users
  # GET /users.json
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @interests = @user.interests
    @own_interests = Interest.where(initiator: @user.id)
  end

  private
  def set_user
    @user = User.find_by(uuid: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    tag = params[:tag]
    link_to title, {sort: column, direction: direction, tag: tag}, {class: css_class}
  end
  
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :warning then "alert alert-warning"
        when :alert then "alert alert-danger"
        else "alert alert-info"
    end
  end
  
  def correct_user?(user)
    user == current_user.id
  end
end

app/helpers/devise_helper.rb
# Solution adapted from
# https://stackoverflow.com/questions/20171539/how-to-apply-customized-bootstrap-messages-errors-to-devise
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="alert alert-danger alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul>#{messages}</ul>
      </div>
      HTML
    html.html_safe
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def show_avatar(user)
    render partial: 'shared/avatar'
  end
end

app/views/users/_form.html.erb
 <%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :old_surname %><br>
    <%= f.text_field :old_surname, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br>
    <%= f.date_select("birth_date", start_year: 1940), class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_new_address_form.html.erb
<div class="row form-inline" id="new_address">
	<%= form_for Address.new, url: addresses_path do |a| %>
		<%= a.text_field :street, class: 'form-control', size: 10, placeholder: 'Street' %>
		<%= a.text_field :number, class: 'form-control', size: 1, placeholder: 'No.' %>
		<%= a.text_field :city_id, class: 'form-control', placeholder: 'City', style: 'width: 20%' %>
		<%= a.text_field :zip, class: 'form-control', size: 5, placeholder: 'Zip' %>
		<%= a.text_field :country_id, class: 'form-control', placeholder: 'Country' %>
		<%= a.text_field :description, class: 'form-control', size: 25, placeholder: 'Description (e.g. Home, Work etc.)' %>
		<button class='btn btn-danger cancel' type="button">Cancel</button>
		<%= a.hidden_field :user_id, {value: current_user.id}%>
		<%= a.submit 'Add!', class: 'form-control btn btn-success'%>
	<% end %>
</div>

app/views/users/_new_contact_form.html.erb
<div class="row form-inline" id="new_contact">
	<%= form_for Contact.new, url: contacts_path do |c| %>
		<%= c.text_field :content, class: 'form-control', size: 10, placeholder: 'Contact' %>
		<%= c.text_field :description, class: 'form-control', size: 25, placeholder: 'Description (e.g. Personal, Work, Abroad etc.)' %>
		<%= c.collection_select(:category_id, Category.all, :id, :name,{class: 'form-control'}, placeholder: 'Type') %>
		<button class='btn btn-danger cancel' type="button">Cancel</button>
		<%= c.hidden_field :user_id, {value: current_user.id}%>
		<%= c.submit 'Add!', class: 'form-control btn btn-success'%>
	<% end %>
</div>

app/views/users/_new_education_form.html.erb
<div class="row form-inline" id="new_education">
	<%= form_for Education.new, url: educations_path do |e| %>
		<%= e.text_field :school, class: 'form-control', placeholder: 'School name', size: 7 %>
		<%= e.text_field :start_date, class: 'form-control generic_date_picker', placeholder: 'Start date', size: 3, 'data-provider' => 'datepicker' %>
		<%= e.text_field :end_date, class: 'form-control generic_date_picker', placeholder: 'End date', size: 3, 'data-provider' => 'datepicker' %>
		<%= e.text_field :field, class: 'form-control', placeholder: 'Field (e.g. Mechanical engineering)' %>
		<%= e.text_field :grade, class: 'form-control', placeholder: 'Grade', size: 1 %>
		<%= e.text_field :activities, class: 'form-control', placeholder: 'Activities (e.g. BEST volunteer)' %>
		<%= e.text_field :description, class: 'form-control', placeholder: 'Description (e.g. MSc, PhD etc.)' %>
		<button class='btn btn-danger cancel' type="button">Cancel</button>
		<%= e.hidden_field :user_id, {value: current_user.id}%>
		<%= e.submit 'Add!', class: 'form-control btn btn-success'%>
	<% end %>
</div>

app/views/users/_new_experience_form.html.erb
<div class="row form-inline" id="new_experience">
	<%= form_for Experience.new, url: experiences_path do |e| %>
		<%= e.text_field :title, class: 'form-control', size: 10, placeholder: 'Title (e.g. Project manager)' %>
		<%= e.text_field :company_id, class: 'form-control', placeholder: 'Company', style: 'width: 20%' %>
		<%= e.text_field :start_date, class: 'form-control generic_date_picker', 'data-provider' => 'datepicker', placeholder: 'Start date' %>
		<%= e.text_field :end_date, class: 'form-control generic_date_picker', 'data-provider' => 'datepicker', placeholder: 'End date' %>
		<%= e.text_field :field_of_work, class: 'form-control', placeholder: 'Field' %>
		<%= e.text_field :city_id, class: 'form-control', placeholder: 'City', style: 'width: 20%' %>
		<%= e.text_field :country_id, class: 'form-control', placeholder: 'Country' %>
		<%= e.text_field :description, class: 'form-control', placeholder: 'Description (e.g. internship)' %>
		<button class='btn btn-danger cancel' type="button">Cancel</button>
		<%= e.hidden_field :user_id, {value: current_user.id}%>
		<%= e.submit 'Add!', class: 'form-control btn btn-success'%>
	<% end %>
</div>

app/views/users/_new_language_form.html.erb
<div class="row form-inline" id="new_language">
	<%= form_for Language.new, url: languages_path do |l| %>
		<%= l.text_field :name, class: 'form-control', placeholder: 'Language', style: 'width: 20%'%>
		<%= l.number_field :level, {value: nil, min: 0, max: 5, class: 'form-control', size: 1, placeholder: 'Level from 0 to 5'} %>
		<button class='btn btn-danger cancel' type="button">Cancel</button>
		<%= l.hidden_field :user_id, {value: current_user.id}%>
		<%= l.submit 'Add!', class: 'form-control btn btn-success'%>
	<% end %>
</div>

app/views/users/_new_lbg_form.html.erb
<div class="row form-inline" id="new_language">
	<%= form_for Lbg.new, url: join_lbg_path do |l| %>
		<%= l.collection_select(:id, Lbg.all, :id, :name, {class: 'form-control', placeholder: 'LBG'}) %>
		<button class='btn btn-danger cancel' type="button">Cancel</button>
		<%= l.hidden_field :user_id, {value: current_user.id}%>
		<%= l.submit 'Add!', class: 'form-control btn btn-success'%>
	<% end %>
</div>

app/views/users/_user_details.html.erb
<div class="table-responsive">
  <table class='table table-hover'>
    <thead>
      <tr>
        <% headers.each do |h| %>
          <th><%= h.titleize %></th>
        <% end %>
        <th></th>
      </tr>
    </thead>
    <% if collection == "contact" && subset == "email"%>
      <tr>
        <td><%= mail_to @user.email %></td>
        <td>Primary e-mail</td>
        <td><%= link_to "Edit", edit_user_registration_path if correct_user?(@user) %></td>
      </tr>
    <% end %>
    <% resource.each do |r| %>
      <tr>
        <% columns.each do |c| %>
          <td>
          <% if collection == "contact" && subset == "email" && c == "content" %>
            <%= mail_to r.send(c) %>
          <% elsif collection == "contact" && subset == "website" && c == "content" %>
            <%= link_to r.send(c), r.send(c) %>
          <% elsif collection == "lbg" && c == "name"%>
            <%= link_to r.send(c), lbg_path(r) %>
          <% else %>
      	    <%= r.send(c) %>
      	  <% end %>
      	  </td>
        <% end %>
        <td>
          <% if collection == "lbg" %>
            <%= link_to "Remove", leave_lbg_path(r), method: :post %>
          <% else %>
	        <%= link_to "Remove", eval("#{collection}_path(r)"), method: :delete if correct_user?(r.user_id) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 search-bar">
    <%= search_form_for @q do |f| %>
      <div class="input-group">
        <%= f.search_field :name_or_surname_cont, class: 'form-control', placeholder: 'Search for a bestie' %>
        <%= f.submit "Search", name: 'nil' %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <h1>Listing members</h1>
</div>

<div class="row">
  <table class="table table-hover table-striped table-responsive">
    <thead>
      <tr>
        <th>Full name</th>
        <th>Gender</th>
        <th>Age</th>
        <th>Countries</th>
        <th>Field of work</th>
        <th>Company</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name + ' ' + user.surname, "/users/#{user.uuid}" %></td>
          <td><%= user.gender %></td>
          <td><%= user.age %></td>
          <td><%= user.country %></td>
          <td><%= user.field %></td>
          <td><%= user.company %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1 class="text-center"><%= show_avatar(@user) %> Profile of <%= @user.name %> <%= @user.surname %></h1>

<ul class="nav nav-tabs" id="myTab">
  <li class="active"><a data-target="#personal" data-toggle="tab">Personal Info</a></li>
  <li><a data-target="#best_related" data-toggle="tab">BEST</a></li>
  <li><a data-target="#contact" data-toggle="tab">Contact</a></li>
  <li><a data-target="#professional" data-toggle="tab">Professional</a></li>
  <li><a data-target="#educations" data-toggle="tab">Education</a></li>
  <li><a data-target="#interests" data-toggle="tab">Interests</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="personal">
    Nickname: <%= @user.nickname %></br>
    Old_surname: <%= @user.old_surname %></br>
    Gender: <%= @user.gender %></br>
    Birthdate: <%= @user.birth_date%></br>
    Joined on: <%= @user.created_at.strftime("%Y-%m-%d") %><br>
    <% if correct_user?(@user) %><%= link_to 'Edit', edit_user_registration_path, class: "btn btn-success" %><% end %>
  </div>
  <div class="tab-pane" id="professional">
  	<div class="row">
  	<%= render partial: 'user_details', locals: {collection: 'experience', columns: ['company_name','title','country_id','start_date','end_date','field_of_work'],
  		headers: ['company','title','country','started at','ended at','field of work'], resource: @user.experiences} %>
	</div>
	<% if @user == current_user %>
		<%= render partial: 'new_experience_form' %>
		<div class="row">
			<div class="col-md-1 col-md-offset-5">
				<button class="btn btn-success", id='add_new_experience'>Add new experience</button>
			</div>
		</div>
	<% end %>
  </div>

  <div class="tab-pane" id='educations' >
  	<div class="row">
  		<h3>Education</h3>
  		<%= render partial: 'user_details', locals: {collection: 'education', columns: ['school','grade','start_date','end_date','field'],
  			headers: ['school','grade','started at','ended at','field'], resource: @user.educations} %>
	</div>
	<% if @user == current_user %>
		<%= render partial: 'new_education_form' %>
		<div class="row">
			<div class="col-md-1 col-md-offset-5">
				<button class="btn btn-success", id='add_new_education'>Add new education</button>
			</div>
		</div>
	<% end %>
	<div class="row">
	  	<h3>Languages</h3>
	  	<%= render partial: 'user_details', locals: {collection: 'language', columns: ['name','level'], headers: ['name','level'], resource: @user.languages} %>
	</div>
	<% if @user == current_user %>
		<%= render partial: 'new_language_form' %>
		<div class="row">
			<div class="col-md-1 col-md-offset-5">
				<button class="btn btn-success", id='add_new_language'>Add new language</button>
			</div>
		</div>
	<% end %>
  </div>

  <div class="tab-pane" id='best_related'>
  	<div class="row">
  	  <%= render partial: 'user_details', locals: {collection: 'lbg', columns: ['name'],
	  			headers: ['Local BEST group'], resource: @user.lbgs} %>
  	</div>
  	<% if @user == current_user %>
	  <%= render partial: 'new_lbg_form' %>
      <div class="row">
        <div class="col-md-1 col-md-offset-5">
		  <button class="btn btn-success", id='add_new_lbg'>Add new LBG</button>
	    </div>
	  </div>
    <% end %>
  </div>

  <div class="tab-pane" id="contact">
  	<div class="row">
  		<div class="col-md-4">
		    <h3>E-mail</h3>
		  	<%= render partial: 'user_details', locals: {collection: 'contact', subset: 'email', columns: ['content','description'],
		  		headers: ['email','description'], resource: @user.contacts.where(category_id: 1)} %>
  		</div>
  		<div class="col-md-4">
			<h3>Website</h3>
			<%= render partial: 'user_details', locals: {collection: 'contact', subset: 'website',  columns: ['content','description'],
		  		headers: ['url','description'], resource: @user.contacts.where(category_id: 3)} %>
  		</div>
  		<div class="col-md-4">
  			<h3>Instant messaging</h3>
		  	<%= render partial: 'user_details', locals: {collection: 'contact', subset: 'skype',  columns: ['content','description'],
		  		headers: ['id','description'], resource: @user.contacts.where(category_id: 4)} %>
  		</div>
	</div>
	<% if @user == current_user %>
		<%= render partial: 'new_contact_form' %>
		<div class="row">
			<div class="col-md-1 col-md-offset-5">
				<button class="btn btn-success", id='add_new_contact'>Add new contact detail</button>
			</div>
		</div>
	<% end %>
	<div class="row">
		<div class="col-md-8">
		    <h3>Addresses</h3>
		    <%= render partial: 'user_details', locals: {collection: 'address', columns: ['full_address','description'],
		    	headers: ['address','description'], resource: @user.addresses} %>
	    </div>
	    <div class="col-md-4">
			<h3>Phones</h3>
			<%= render partial: 'user_details', locals: {collection: 'contact', subset: 'phones',  columns: ['content','description'],
	  			headers: ['number','description'], resource: @user.contacts.where(category_id: 2)} %>
		</div>
    </div>
    <% if @user == current_user %>
	    <%= render partial: 'new_address_form'%>
		<div class="row">
			<div class="col-md-1 col-md-offset-5">
				<button class="btn btn-success", id='add_new_address'>Add new address</button>
			</div>
		</div>
	<% end %>
  </div>
  <div class="tab-pane" id="interests">
    This user is part of the following interest groups:
    <ol>
    <% @interests.each do |i| %>
      <li><%= link_to i.title, interest_path(i) %></li>
    <% end %>
    </ol>
    And is the initiator of the following interest groups:
    <ol>
	<% @own_interests.each do |i| %>
      <li><%= link_to i.title, interest_path(i) %> with <%= i.users.count %> member(s)</li>
	<% end %>
    </ol>
  </div>
</div>

<script>
	var cities = [<% City.all.each do |c| %>"<%= c.name %>",<% end %>];
	var companies = [<% Company.all.each do |c| %>"<%= c.name %>",<% end %>];
	var languages = [<% Language.all.each do |l| %>"<%= l.name %>",<% end %>];
</script>