config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  root "users#index"

  resources :search, only: [:index, :show]
  resources :interests
  post 'interest/:id/join', to: 'interests#join', as: 'join_interest'
  post 'interest/:id/leave', to: 'interests#leave', as: 'leave_interest'
  resources :lbgs
  post 'lbg/:id/join', to: 'lbgs#join', as: 'join_lbg'
  post 'lbg/:id/leave', to: 'lbgs#leave', as: 'leave_lbg'

  resources :users, only: [:index, :show]
  resources :announcements
  get 'announcements?tag=:id', to: 'announcements#index', as: 'announcements_tag'

  resources :tags, only: [:index]
  resources :contacts, except: [:index, :show]
  resources :addresses, except: [:index, :show]
  resources :languages, except: [:index, :show]
  resources :educations, except: [:index, :show]
  resources :experiences, except: [:index, :show]
  resources :lbgs, except: [:index, :show]

  post 'comment', to: 'announcements#add_comment', as: 'add_comment'
  delete 'comment/:id', to: 'announcements#del_comment', as: 'del_comment'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :city
  
  def full_address
    country_name = Country.new(self.country_id)
    [self.street, self.number, self.city.name, self.zip, country_name].to_sentence(:last_word_connector => ', ', :two_words_connector => ', ').html_safe
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_taggable

  validates :title, presence: true
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :contact
end

app/models/city.rb
class City < ApplicationRecord
  has_one :experience
  has_one :address
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :announcement
  
  validates :user_id, presence: true
  validates :announcement_id, presence: true
  validates :body, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_one :experience
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_one :category
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  belongs_to :city
  belongs_to :company

  def company_name
    self.company.name
  end
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :user
end

app/models/lbg.rb
class Lbg < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/search.rb
class Search < ApplicationRecord
  
  def users
    @users ||= find_users
  end

  def self.for(id_search, name, surname, old_surname, nickname)

    # escape for security
    name        = "%#{name}%"
    surname     = "%#{surname}%"
    old_surname = "%#{old_surname}%"
    nickname    = "%#{nickname}%"

    users = User.order(:name)
    users = users.where(id: id_search) if id_search.present?
    users = users.where("name like ?", "%#{name}%") if name.present?
    users = users.where("surname like ?", "%#{surname}%") if surname.present?
    users = users.where("old_surname like ?", "%#{old_surname}%") if old_surname.present?
    users = users.where("nickname like ?", "%#{nickname}%") if nickname.present?
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :announcements
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses
  has_many :educations
  has_many :contacts
  has_many :experiences
  has_many :languages
  has_many :announcements
  has_many :comments
  has_and_belongs_to_many :lbgs
  has_and_belongs_to_many :interests
  validates :uuid, uniqueness: true
  validates :name, presence: true
  validates :surname, presence: true
  validates :birth_date, presence: true

  enum gender: ["Male","Female","Other"]

  def age
    (Date.today - self.birth_date).to_i / 365
  end

  def country
    @countries = Array.new
    @addresses = self.addresses
    @addresses.each do |a|
      @countries << Country.new(a.country_id).name
    end
    @countries.to_sentence
  end

  def field
    @fields = Array.new
    @experiences = self.experiences
    @experiences.each do |e|
      @fields << e.field_of_work
    end
    @fields.to_sentence
  end

  def company
    @companies = Array.new
    @experiences = self.experiences
    @experiences.each do |e|
      @companies << e.company.name
    end
    @companies.to_sentence
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :is_member?, :only => :show

  def index
    @interests = Interest.all
  end

  def show
    @is_member = is_member?
  end

  def edit
    @interest = Interest.find(params[:id])
  end

  def new
    @interest = Interest.new
  end

  def create
    @interest = Interest.new(interest_params)
    if @interest.save!
      flash[:success]="You created new interest successfully!"
      redirect_to interests_path
    else
     flash[:alert]="Something went wrong :( Please report this bug at admin@aludir.net"
     render_to new_interest_path
    end
  end

  def update
    @interest = Interest.find(params[:id])

    if @interest.update(interest_params)
      flash[:success]="You updated your interest group successfully!"
      redirect_to @interest
    else
      flash[:alert]="Something went wrong :( Please report this bug at admin@aludir.net"
      render 'edit'
    end
  end

  def join
    if is_member?
      flash[:alert]='You are already part of this group'
    else
      flash[:success]='You joined this interest group!'
      @interest.users<< current_user
    end
    redirect_to interest_path(params[:id])
  end

  def leave
    if is_member?
      flash[:notice]='You left this group'
      @interest.users.destroy(current_user)
    else
      flash[:alert]='You are not part of this group'
    end
    redirect_to interest_path(params[:id])
  end

  private

  def interest_params
    params.require(:interest).permit(:initiator, :title, :description)
  end

  def sort_column
    Interest.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end

  def is_member?
    @interest = Interest.find(params[:id])
    @interest.users.exists?(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    tag = params[:tag]
    link_to title, {sort: column, direction: direction, tag: tag}, {class: css_class}
  end
  
  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :warning then "alert alert-warning"
        when :alert then "alert alert-danger"
        else "alert alert-info"
    end
  end
  
  def correct_user?(user)
    user == current_user.id
  end
end

app/helpers/devise_helper.rb
# Solution adapted from
# https://stackoverflow.com/questions/20171539/how-to-apply-customized-bootstrap-messages-errors-to-devise
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="alert alert-danger alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul>#{messages}</ul>
      </div>
      HTML
    html.html_safe
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def show_avatar(user)
    render partial: 'shared/avatar'
  end
end

app/views/interests/_form.html.erb
<div class="row">
  <div class="col-md-10">
  	<%= form_for (@interest) do |f| %>
  		
  	  <div class="form-group">
	  	<%= f.label :title %>
	    <%= f.text_field :title, required: 'required', placeholder: 'Title', class: 'form-control' %>
	  </div>
	  <div class="form-group">
	  	<%= f.label :description %>
	    <%= f.text_area :description, required: 'required', placeholder: 'Description', class: 'form-control', rows: 10 %>
	  </div>
	  
	  <%= f.hidden_field :initiator, {value: current_user.id} %>
	  <% if dom_id == "edit_announcement"%>
	    <%= button_to "Edit!", edit_interest_path(@interest), class: "btn btn-success" %>
	  <%else%>
	    <%= f.submit "Create", class: "btn btn-success" %>
	  <%end%>
	<%end%>
  </div>
</div>

app/views/interests/edit.html.erb
<%= render 'form', dom_id: 'edit_announcement'%>

app/views/interests/index.html.erb
  <div class="row">
  	<div class="col-md-10">
  	<h2>Interests</h2>
	  <div class="table-responsive">
	  <table class='table table-hover'>
	    <thead>
	      <tr>
	        <th><%= sortable 'title' %></th>
	        <th>Initiator</th>
	        <th>Members</th>
	        <th><%= sortable 'created_at', 'Date'%></th>
	      </tr>
	    </thead>
	
	    <tbody> 
	      <% @interests.each do |interest| %>
	        <tr>
	          <td><%= link_to interest.title, interest_path(interest) %></td>
	          <% @user = User.find(interest.initiator) %>
	          <td><%= link_to @user.name+' '+@user.surname, "/users/#{@user.uuid}" %></td>
	          <td><%= interest.users.count %></td>
	          <td><%= interest.created_at.strftime("%Y-%m-%d") %></td>
	        </tr>
	      <% end %>
	    </tbody>
	  </table>
	</div>
	<center><%= link_to 'Create new interest', new_interest_path, class: 'btn btn-success'%></center>
	</div>
  </div>

app/views/interests/new.html.erb
<%= render 'form', dom_id: 'new_announcement'%>

app/views/interests/show.html.erb
<div class="row">
  <div class="col-md-10">
    <div class="row">
      <h2><%= @interest.title %></h2>
      <div class="well col-md-4">
		<% @user = User.find(@interest.initiator)%>
		By: <%= link_to @user.name+' '+@user.surname, user_path(@user.uuid) %>
		<br>
		Address: <%= @interest.title %>@aludir.net
		<br>
        Created on: <%= @interest.created_at.strftime("%Y-%m-%d") %>
        <br>
        Description: <%= @interest.description %>
        <% if @interest.initiator == current_user.id %>
          <%= link_to 'edit now?', edit_interest_path %>
        <% end %>
      </div>
    </div>
    <% if @is_member %>
    	<%= link_to 'Leave the group', leave_interest_path(@interest), method: :post, class: 'btn btn-danger'%>
    <% else %>
    	<%= link_to 'Join the group', join_interest_path(@interest), method: :post, class: 'btn btn-success'%>
    <% end %>
    <div class="row">
      <h2>Members</h2>
      <ol>
      	<% @interest.users.each do |u| %>
      	  <li><%= link_to u.name+' '+u.surname, user_path(u.uuid) %></li>
      	<% end %>
      </ol>
    </div>
  </div>
</div>