config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  root "users#index"

  resources :search, only: [:index, :show]
  resources :interests
  post 'interest/:id/join', to: 'interests#join', as: 'join_interest'
  post 'interest/:id/leave', to: 'interests#leave', as: 'leave_interest'
  resources :lbgs
  post 'lbg/:id/join', to: 'lbgs#join', as: 'join_lbg'
  post 'lbg/:id/leave', to: 'lbgs#leave', as: 'leave_lbg'

  resources :users, only: [:index, :show]
  resources :announcements
  get 'announcements?tag=:id', to: 'announcements#index', as: 'announcements_tag'

  resources :tags, only: [:index]
  resources :contacts, except: [:index, :show]
  resources :addresses, except: [:index, :show]
  resources :languages, except: [:index, :show]
  resources :educations, except: [:index, :show]
  resources :experiences, except: [:index, :show]
  resources :lbgs, except: [:index, :show]

  post 'comment', to: 'announcements#add_comment', as: 'add_comment'
  delete 'comment/:id', to: 'announcements#del_comment', as: 'del_comment'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :city
  
  def full_address
    country_name = Country.new(self.country_id)
    [self.street, self.number, self.city.name, self.zip, country_name].to_sentence(:last_word_connector => ', ', :two_words_connector => ', ').html_safe
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_taggable

  validates :title, presence: true
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :contact
end

app/models/city.rb
class City < ApplicationRecord
  has_one :experience
  has_one :address
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :announcement
  
  validates :user_id, presence: true
  validates :announcement_id, presence: true
  validates :body, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  has_one :experience
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_one :category
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  belongs_to :city
  belongs_to :company

  def company_name
    self.company.name
  end
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :user
end

app/models/lbg.rb
class Lbg < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/search.rb
class Search < ApplicationRecord
  
  def users
    @users ||= find_users
  end

  def self.for(id_search, name, surname, old_surname, nickname)

    # escape for security
    name        = "%#{name}%"
    surname     = "%#{surname}%"
    old_surname = "%#{old_surname}%"
    nickname    = "%#{nickname}%"

    users = User.order(:name)
    users = users.where(id: id_search) if id_search.present?
    users = users.where("name like ?", "%#{name}%") if name.present?
    users = users.where("surname like ?", "%#{surname}%") if surname.present?
    users = users.where("old_surname like ?", "%#{old_surname}%") if old_surname.present?
    users = users.where("nickname like ?", "%#{nickname}%") if nickname.present?
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :announcements
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses
  has_many :educations
  has_many :contacts
  has_many :experiences
  has_many :languages
  has_many :announcements
  has_many :comments
  has_and_belongs_to_many :lbgs
  has_and_belongs_to_many :interests
  validates :uuid, uniqueness: true
  validates :name, presence: true
  validates :surname, presence: true
  validates :birth_date, presence: true

  enum gender: ["Male","Female","Other"]

  def age
    (Date.today - self.birth_date).to_i / 365
  end

  def country
    @countries = Array.new
    @addresses = self.addresses
    @addresses.each do |a|
      @countries << Country.new(a.country_id).name
    end
    @countries.to_sentence
  end

  def field
    @fields = Array.new
    @experiences = self.experiences
    @experiences.each do |e|
      @fields << e.field_of_work
    end
    @fields.to_sentence
  end

  def company
    @companies = Array.new
    @experiences = self.experiences
    @experiences.each do |e|
      @companies << e.company.name
    end
    @companies.to_sentence
  end
end

app/helpers/devise_helper.rb
# Solution adapted from
# https://stackoverflow.com/questions/20171539/how-to-apply-customized-bootstrap-messages-errors-to-devise
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="alert alert-danger alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul>#{messages}</ul>
      </div>
      HTML
    html.html_safe
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def show_avatar(user)
    render partial: 'shared/avatar'
  end
end

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class="container">
        <p class="text-muted credit">Contact <a href="mailto:admin@aludir.net">AluDir</a>.</p>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">AluDir</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Lbgs', lbgs_path %></li>
        <li><%= link_to(announcements_path) do %>
        Announcements <span class="badge" data-toggle="tooltip" data-placement="right" title="New announcements since your last visit!"><%= @announce_count%></span><%end%></li>
        <li><%= link_to 'Interests', interests_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Edit my details', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AluDir</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
  <% if user_signed_in? %>
    <%= render 'layouts/navbar' %>
    <%= render "layouts/messages" %>

  <% end %>


  <div class="container">
    <%= yield %>
  </div>


<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//www.natsakis.com/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 3]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//www.natsakis.com/piwik/piwik.php?idsite=3" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->

</body>
</html>

app/views/shared/_avatar.html.erb
<div class="avatar-circle">
  <span class="initials">
    <%= @user.name[0].upcase + @user.surname[0].upcase %>
  </span>
</div>